export var SETTLEMENT_TRANSACTIONS = "SETTLEMENT_TRANSACTIONS";
export const USER_DATA = "USER_DATA";
export const USER_DATA_TEMP = "USER_DATA_TEMP";
export const LOGIN = "LOGIN";
export const ERROR_DATA = "ERROR_DATA";
export const BANK_DETAILS = "BANK_DETAILS";
export const BANK_LIST = "BANK_LIST";
export const BUSINESS_DETAILS = "BUSINESS_DETAILS";
export const BUSINESS_ANALYTICS = "BUSINESS_ANALYTICS";
export const TRANSACTIONS = "TRANSACTIONS";
export const TRANSACTION_OVERVIEW = "TRANSACTION_OVERVIEW";
export const SAMPLE_TRANSACTIONS = "SAMPLE_TRANSACTIONS";
export const SINGLE_TRANSACTIONS = "SINGLE_TRANSACTIONS";
export const CUSTOMERS_TRANSACTIONS = "CUSTOMERS_TRANSACTIONS";
export const REFUNDS = "REFUNDS";
export const REFUND = "REFUND";
export const DISPUTES = "DISPUTES";
export const DISPUTE = "DISPUTE";
export const SINGLE_DISPUTE = "SINGLE_DISPUTE";
export const CUSTOMERS = "CUSTOMERS";
export const SUCCESS_DATA = "SUCCESS_DATA";
export const PAYOUTS = "PAYOUTS";
export const INTERNATIONAL_PAYOUTS = "INTERNATIONAL_PAYOUTS";
export const PERMISSIONS = "PERMISSIONS";
export const PRODUCTS = "PRODUCTS";
export const PRODUCT_CATEGORIES = "PRODUCT_CATEGORIES";
export const RECOVER_PASSWORD = "RECOVER_PASSWORD";
export const PASSWORD_RESET = "PASSWORD_RESET";
export const INDUSTRY_LIST = "INDUSTRY_LIST";
export const ROLES = "ROLES";
export const ROLE = "ROLE";
export const USERS = "USERS";
export const USER = "USER";
export const TRANSACTION_RANGE = "TRANSACTION_RANGE";
export const BUSINESS_USERS = "BUSINESS_USERS";
export const ALL_TRANSACTIONS = "ALL_TRANSACTIONS";
export const BRANCH_TRANSACTIONS = "BRANCH_TRANSACTIONS";
export const BRANCH_SUMMARY = "BRANCH_SUMMARY";
export const INVITE_USER = "INVITE_USER";
export const RESET_KEYS = "RESET_KEYS";
export const USER_PERMISSION = "USER_PERMISSION";
export const SEARCHING_TRANSACTIONS = "SEARCHING_TRANSACTIONS";
export const SEARCHING_REFUNDS = "SEARCHING_TRANSACTIONS";
export const DISPUTES_SEARCH_RESULT = "DISPUTES_SEARCH_RESULT";
export const PAYOUTS_SEARCH_RESULT = "PAYOUTS_SEARCH_RESULT";
export const REFUNDS_SEARCH_RESULT = "REFUNDS_SEARCH_RESULT";
export const RELEASE_NOTES = "RELEASE_NOTES";
export const ADD_TRANS_REPORT = "ADD_TRANS_REPORT";
export const ADD_TRANS_REPORT_BOTTOM = "ADD_TRANS_REPORT_BOTTOM";
export const REMOVE_TRANS_REPORT = "REMOVE_TRANS_REPORT";
export const REMOVE_TRANS_REPORT_BOTTOM = "REMOVE_TRANS_REPORT_BOTTOM";
export const RESET_TRANS_REPORT = "RESET_TRANS_REPORT";
export const MOVE_OUT_TRANS_FIELD = "MOVE_OUT_TRANS_FIELD";
export const MOVE_IN_TRANS_FIELD = "MOVE_IN_TRANS_FIELD";
export const EMAIL_REPORT = "EMAIL_REPORT";
export const COUNTRIES = "COUNTRIES";
export const LOADING_COUNTRIES = "LOADING_COUNTRIES";
export const BUSINESS = "BUSINESS";
export const NEW_BUSINESS = "NEW_BUSINESS";
export const CURENCY_MODE = "CURENCY_MODE";
export const BUSINESS_KEY = "BUSINESS_KEY";
export const KYC = "KYC";
export const BRANCH_MANAGER = "BRANCH_MANAGER";
export const BRANCH = "BRANCH";
export const NAME_INQUIRY = "NAME_INQUIRY";
export const PAYMENT_LINK = "PAYMENT_LINK";
export const PAYMENT_LINK_DELETE = "PAYMENT_LINK_DELETE";
export const LOADING_PAYMENT_LINK_DELETE = "LOADING_PAYMENT_LINK_DELETE";
export const WHITE_LABEL = "WHITE_LABEL";
export const BRANCH_PAYOUT = "BRANCH_PAYOUT";
export const BRANCH_SETTLEMENTS = "BRANCH_SETTLEMENTS";
export const SETTLEMENT_DETAILS = "SETTLEMENT_DETAILS";
export const PRODUCT = "PRODUCT";
export const CATEGORY = "CATEGORY";
export const WALLET = "WALLET";
export const WALLETS = "WALLETS";
export const POCKETCUSTOMERS = "ADDPOCKETCUSTOMER";
export const POCKETCUSTOMERSTRANSACTIONS = "POCKETCUSTOMERSTRANSACTIONS";
export const QUERY = "QUERY";
export const UPDATE = "UPDATE";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";

//FRONT STORE TYPES
export const GET_BUSINESS_STORES = "GET_BUSINESS_STORES";
export const LOADING_BUSINESS_STORES = "LOADING_BUSINESS_STORES";
export const LOADING_BUSINESS_PRODUCTS = "LOADING_BUSINESS_PRODUCTS";
export const BUSINESS_PRODUCTS = "BUSINESS_PRODUCTS";
export const LOADING_STORE_ORDERS = "LOADING_STORE_ORDERS";
export const STORE_ORDERS = "STORE_ORDERS";
export const LOADING_STORE_PRODUCTS = "LOADING_STORE_PRODUCTS";
export const STORE_PRODUCTS = "STORE_PRODUCTS";

//USERS TYPES
export const LOADING_BUSINESS_USERS = "LOADING_BUSINESS_USERS";
export const BUSINESS_USERS_LIST = "BUSINESS_USERS_LIST";
export const UPDATE_SINNGLE_BUSINESS_USER = "UPDATE_SINNGLE_BUSINESS_USER";

export const LOADING_TRANSACTIONS = "LOADING_TRANSACTIONS";
export const LOADING_RECENT_TRANSACTIONS = "LOADING_RECENT_TRANSACTIONS";
export const RECENT_TRANSACTIONS = "RECENT_TRANSACTIONS";
export const DASHBOARD_ANALYTICS = "DASHBOARD_ANALYTICS";
export const LOADING_DASHBOARD_ANALYTICS = "LOADING_DASHBOARD_ANALYTICS";
export const UPDATE_SINGLE_BUSINESS = "UPDATE_SINGLE_BUSINESS";
export const UPDATE_SINGLE_CHECKOUT_AD = "UPDATE_SINGLE_CHECKOUT_AD";

export const SET_CHECKOUT_ADS = "SET_CHECKOUT_ADS";
export const LOADING_CHECKOUT_ADS = "LOADING_CHECKOUT_ADS";

export const SETTLEMENTS = "SETTLEMENTS";
export const LOADING_SETTLEMENTS = "LOADING_SETTLEMENTS";
export const SET_ROLE = "SET_ROLE";

//Recurring

export const LOADING_SUBSCRIPTIONS = "LOADING_SUBSCRIPTIONS";
export const SUBSCRIPTIONS = "SUBSCRIPTIONS";
export const UPDATE_SINGLE_SUBSCRIPTION = "UPDATE_SINGLE_SUBSCRIPTION";

export const LOADING_PLANS = "LOADING_PLANS";
export const PLANS = "PLANS";
export const CREATE_PLAN = "CREATE_PLAN";
export const LOADING_SUBSCRIBERS = "LOADING_SUBSCRIBERS";
export const SUBSCRIBERS = "SUBSCRIBERS";
export const PLAN_SUBSCRIBERS = "PLAN_SUBSCRIBERS";
export const LOADING_PLAN_SUBSCRIBERS = "LOADING_PLAN_SUBSCRIBERS";
export const SUBSCRIBER_TRANSACTIONS = "SUBSCRIBER_TRANSACTIONS";
export const LOADING_SUBSCRIBER_TRANSACTIONS =
  "LOADING_SUBSCRIBER_TRANSACTIONS";
export const UPDATE_SINGLE_PLAN = "UPDATE_SINGLE_PLAN";
export const LOADING_SUBSCRIBER_SUBSCRIPTIONS =
  "LOADING_SUBSCRIBER_SUBSCRIPTIONS";
export const SUBSCRIBER_SUBSCRIPTIONS = "SUBSCRIBER_SUBSCRIPTIONS";

export const LOADING_COUNTRY_KYC = "LOADING_COUNTRY_KYC";
export const COUNTRY_KYC = "COUNTRY_KYC";
export const BLOCK_UI = "BLOCK_UI";

export const BUSINESS_LIST = "BUSINESS_LIST";
export const USER_AUTHENTICATION = "USER_AUTHENTICATION";
export const PAYMENT_LINKS = "PAYMENT_LINKS";
export const LOADING_PAYMENT_LINKS = "LOADING_PAYMENT_LINKS";
export const LOADING_PAYMENT_LINK_TRANSACTIONS =
  "LOADING_PAYMENT_LINK_TRANSACTIONS";
export const PAYMENT_LINK_TRANSACTIONS = "PAYMENT_LINK_TRANSACTIONS";

//POCKET ACTIONS
export const LOADING_POCKET_CUSTOMERS = "LOADING_POCKET_CUSTOMERS";
export const SET_POCKET_CUSTOMERS = "SET_POCKET_CUSTOMERS";
export const LOADING_POCKET_TRANSACTIONS = "LOADING_POCKET_TRANSACTIONS";
export const NEW_PRODUCT_ID = "NEW_PRODUCT_ID";
export const POCKET_PROFILE_DEBIT = "POCKET_PROFILE_DEBIT";
export const LOADING_POCKET_PROFILE_DEBIT = "LOADING_POCKET_PROFILE_DEBIT";
export const POCKET_PROFILE_CREDIT = "POCKET_PROFILE_CREDIT";
export const LOADING_POCKET_PROFILE_CREDIT = "LOADING_POCKET_PROFILE_CREDIT";
export const TRANSACTION_CUSTOM_FIELD_NAMES = "TRANSACTION_CUSTOM_FIELD_NAMES";
export const BUSINESS_POCKET_HISTORY = "BUSINESS_POCKET_HISTORY";
export const LOADING_BUSINESS_POCKET_HISTORY =
  "LOADING_BUSINESS_POCKET_HISTORY";
export const LOADING_BUSINESS_POCKET_BALANCE =
  "LOADING_BUSINESS_POCKET_BALANCE";
export const BUSINESS_POCKET_BALANCE = "BUSINESS_POCKET_BALANCE";
export const BUSINESS_POCKET_TRANSFERS = "BUSINESS_POCKET_TRANSFERS";
export const LOADING_BUSINESS_POCKET_TRANSFERS =
  "LOADING_BUSINESS_POCKET_TRANSFERS";
export const LOADING_SUB_POCKETS_HISTORY = "LOADING_SUB_POCKETS_HISTORY";
export const SUB_POCKETS_HISTORY = "SUB_POCKETS_HISTORY";
export const LOADING_BUSINESS_SUB_POCKETS = "LOADING_BUSINESS_SUB_POCKETS";
export const BUSINESS_SUB_POCKETS = "BUSINESS_SUB_POCKETS";
export const GET_ON_BOARDING_STATUS = "GET_ON_BOARDING_STATUS";
export const ON_BOARDING = "onboarding";
export const LANGUAGE = "LANGUAGE";
export const USER_PERMISSIONS = "USER_PERMISSIONS";

//Invoice
export const INVOICE_CUSTOMERS = "INVOICE_CUSTOMERS";
export const LOADING_INVOICE_CUSTOMERS = " LOADING_INVOICE_CUSTOMERS";
export const INVOICES = "INVOICES";
export const LOADING_INVOICES = "LOADING_INVOICES";
export const INVOICE_NUMBER = "INVOICE_NUMBER";
export const GENERATING_INVOICE_NUMBER = "GENERATING_INVOICE_NUMBER";
export const LOADING_INVOICE_0VERVIEW = "LOADING_INVOICE_0VERVIEW";
export const INVOICE_0VERVIEW = "INVOICE_0VERVIEW";
export const CREATING_INVOICE = "CREATING_INVOICE";

export const FETCH_POS_TERMINALS = "FETCH_POS_TERMINALS";
export const LOADING_TERMINALS = "LOADING_TERMINALS";

export const SAVE_TWO_FACTOR = "SAVE_TWO_FACTOR";

export const BUSINESS_PRODUCT_CATEGORIES = 'product_categories'
export const LOADING_ORDERS_BY_PRODUCT = 'LOADING_ORDERS_BY_PRODUCT'
export const PRODUCT_ORDERS = 'PRODUCT_ORDERS'
export const PRODUCT_DETAILS = 'PRODUCT_DETAILS';

// POS Web
export const posTerminalTypes = {
  GET_TERMINALS: "GET_TERMINALS",
}

//PROD
export const BASE_URL = 'https://merchant.seerbitapi.com/springmerchants/api/v1/';
export const BASE_URL_AUTH_SERVICE = 'https://merchant.seerbitapi.com/authservice/api/v1/'
export const BASE_URL_INVOICE = 'https://merchant.seerbitapi.com/invoice/api/v1/';
export const BASE_URL_STORE = 'https://merchant.seerbitapi.com/store/api/v1/';
export const SLACK_URL = '';
export const PARTNER_ID = 1;

