export const navigationMenuConfig = [
  {
    id: "home",
    title: "Home",
    type: "item",
    icon: null,
    permissions: ["*"],
    navLink: "/#",
  },
  {
    id: "payments",
    title: "Payments",
    type: "collapse",
    icon: null,
    permissions: ["*"],
    navLink: "",
    hasSections: false,
    hasChildren: true,
    children: [

          {
            id: "transactions",
            title: "Transactions",
            type: "item",
            icon: null,
            permissions: ["*"],
            navLink: "/payments/transactions",
          },
          {
            id: "payment_link",
            title: "Payment Links",
            type: "item",
            icon: null,
            permissions: ["*"],
            navLink: "/payments/links",
          },
          {
            id: "branch_transactions",
            title: "Branch Transactions",
            type: "item",
            icon: null,
            permissions: ["ACCESS_BRANCHES"],
            navLink: "/transactions/branches",
          },
          {
            id: "payment_customers",
            title: "Customers",
            type: "item",
            icon: null,
            permissions: ["*"],
            navLink: "/transactions/customers",
          },
          // {
          //     id: "pocket_customers",
          //     title: "Pocket Customers",
          //     type: "item",
          //     icon: null,
          //     permissions: [],
          //     navLink: "/customer-pockets",
          // },
        ],

      // {
      //   section: "actions",
      //   children: [
      //     {
      //       id: " payment_link",
      //       title: "Payment Links",
      //       type: "item",
      //       icon: null,
      //       permissions: ["*"],
      //       navLink: "/payment/links",
      //     },
      //   ],
      // },
  },
  {
    id: "finance",
    title: "Finance",
    type: "collapse",
    icon: null,
    permissions: ["*"],
    navLink: "",
    hasSections: false,
    hasChildren: true,
    children: [
      {
        id: "settlements",
        title: "Settlements",
        type: "item",
        icon: null,
        permissions: ["*"],
        navLink: "/settlements",
      },
      {
        id: "split-settlements",
        title: "Split Settlements",
        type: "item",
        icon: null,
        permissions: ["*"],
        navLink: "/split-settlements",
      },
      {
        id: "refunds",
        title: "Refunds",
        type: "item",
        icon: null,
        permissions: ["*"],
        navLink: "/refunds",
      },
      {
        id: "disputes",
        title: "Disputes",
        type: "item",
        icon: null,
        permissions: ["*"],
        navLink: "/disputes",
      },
    ],
  },
  {
    id: "store",
    title: "Store",
    type: "collapse",
    icon: null,
    permissions: ["*"],
    navLink: "",
    hasSections: false,
    hasChildren: true,
    children: [
      {
        id: "products",
        title: "Products",
        type: "item",
        icon: null,
        permissions: ["*"],
        navLink: "/products",
      },
      {
        id: "product-categories",
        title: "Product Categories",
        type: "item",
        icon: null,
        permissions: ["*"],
        navLink: "/products/categories",
      },
      // {
      //   id: "front-store",
      //   title: "Front Store",
      //   type: "item",
      //   icon: null,
      //   permissions: ["*"],
      //   navLink: "/frontstore",
      // },
    ],
  },
  {
    id: "pocket",
    title: "Pocket",
    type: "collapse",
    icon: null,
    permissions: ["*"],
    navLink: "#/pocket",
    hasSections: false,
    hasChildren: false,
    children: [
      {
        id: "pockets",
        title: "Pockets",
        type: "item",
        icon: null,
        permissions: ["*"],
        navLink: "/pocket",
      },
    ],
  },
  {
    id: "recurring",
    title: "Recurring",
    type: "collapse",
    icon: null,
    permissions: ["*"],
    navLink: "",
    hasSections: false,
    hasChildren: true,
    children: [
      //         {
      //             id: "subscriptions",
      //             title: "Subscriptions",
      //             type: "item",
      //             icon: null,
      //             permissions: [],
      //             navLink: "/subscriptions",
      //         },
      //         // {
      //         //     id: "plans",
      //         //     title: "Plans",
      //         //     type: "item",
      //         //     icon: null,
      //         //     permissions: [],
      //         //     navLink: "/plans",
      //         // },
      //     ],
      // },
      // {
      //     id: "subscriptions",
      //     title: "Subscriptions",
      //     type: "item",
      //     icon: null,
      //     permissions: [],
      //     navLink: "/subscriptions",
      // },
      {
        id: "plans",
        title: "Plans",
        type: "item",
        icon: null,
        permissions: ["*"],
        navLink: "/plans",
      },
      {
        id: "subscribers",
        title: "Subscribers",
        type: "item",
        icon: null,
        permissions: ["*"],
        navLink: "/subscribers",
      },
    ],
  },
  // {
  //   id: "invoice",
  //   title: "Invoice",
  //   type: "collapse",
  //   icon: null,
  //   permissions: [],
  //   navLink: "#/invoice",
  //   hasSections: false,
  //   hasChildren: false,
  //   children: [],
  // },
  {
    id: "account",
    title: "Account",
    type: "collapse",
    icon: null,
    permissions: ["*"],
    navLink: "",
    hasSections: false,
    hasChildren: true,
    children: [
      {
        id: "settings",
        title: "Settings",
        type: "item",
        icon: null,
        permissions: ["*"],
        navLink: "/account",
      },
    ],
  },
];
