export const navigationMenuConfig = [
  {
    id: "home",
    title: "Home",
    type: "item",
    icon: null,
    permissions: ["*"],
    navLink: "/",
  },
  {
    id: "transactions",
    title: "Transactions",
    type: "item",
    icon: null,
    permissions: ["*"],
    navLink: "#/payments/transactions",
  },
  {
    id: "finance",
    title: "Finance",
    type: "collapse",
    icon: null,
    permissions: ["*"],
    navLink: "",
    hasSections: false,
    hasChildren: true,
    children: [
      {
        id: "settlements",
        title: "Settlements",
        type: "item",
        icon: null,
        permissions: ["*"],
        navLink: "/settlements",
      },
      {
        id: "refunds",
        title: "Refunds",
        type: "item",
        icon: null,
        permissions: ["*"],
        navLink: "/refunds",
      },
      {
        id: "disputes",
        title: "Disputes",
        type: "item",
        icon: null,
        permissions: ["*"],
        navLink: "/disputes",
      },
    ],
  },
  {
    id: "account",
    title: "Account",
    type: "collapse",
    icon: null,
    permissions: ["*"],
    navLink: "",
    hasSections: false,
    hasChildren: true,
    children: [
      {
        id: "settings",
        title: "Settings",
        type: "item",
        icon: null,
        permissions: ["*"],
        navLink: "/account",
      },
    ],
  },
];
