// /**
//  * Pin Code
//  *
//  * @format
//  */
//
// import React, { useState, useEffect } from "react";
// import { connect } from "react-redux";
// import { userLogin, setErrorLog } from "../../actions/postActions";
// import cogoToast from "cogo-toast";
// import { Button, Spinner } from "react-bootstrap";
// import ReactCodeInput from "react-code-input";
// import "./css/index.scss";
// import SeerBitAdverts from "../../components/seerbitAdverts";
//
// const codeInputProps = {
//     inputStyle: {
//         textAlign: "center",
//         margin: '0 6px',
//         width: '50px',
//         borderRadius: '3px',
//         fontSize: '20px',
//         height: '50px',
//         border: '1px solid #253B80'
//     },
//     inputStyleInvalid: {
//         textAlign: "center",
//         margin: '5px',
//         width: '50px',
//         borderRadius: '3px',
//         fontSize: '20px',
//         height: '50px',
//         color: 'red',
//         border: '1px solid red'
//     }
// }
//
// export function PinCode(props) {
//     const { history } = props;
//     const [value, setValue] = useState(null);
//     const [inProcess, setInProcess] = useState(false);
//     const [hasBackUpCode, setHasBackUpCode] = useState(false);
//
//     useEffect(() => {
//         props.setErrorLog();
//     }, []);
//
//     useEffect(() => {
//         if (props.error_details && props.error_details.error_source === "login") {
//             setInProcess(false);
//             cogoToast.error(props.error_details.message, { position: "top-right" });
//         }
//     }, [props.user_details, props.error_details, props.white_label]);
//
//     const handleValue = (e) => {
//         setValue({ ...value, [e.target.name]: e.target.value });
//     };
//
//     const initAuthorization = async (e, email, password) => {
//         e.preventDefault();
//
//         const params = {
//             data: { email, password },
//             location: "login",
//         };
//
//         props.userLogin(params);
//     };
//
//
//     return (
//         <div className="p-0 sbt-reset ">
//             <div className="d-flex justify-content-between">
//                 <div className="auth--container">
//                     <img
//                         src="https://res.cloudinary.com/dpejkbof5/image/upload/v1620323718/Seerbit_logo_png_ddcor4.png"
//                         as="a"
//                         href="https://seerbit.com/"
//                         target="_blank"
//                         className="auth-logo"
//                     />
//                     <div
//                         className="auth--section row"
//                     >
//                         <div className="col-md-6 col-sm-12">
//                         <form
//                             className="w-100"
//                             onSubmit={(e) => {
//                                 e.preventDefault();
//                                 setInProcess(true);
//                                 //initAuthorization(e, email, password);
//                             }}
//                         >
//                             <div className="my-5">
//                                 <div className="title" >Two-factor Login</div>
//                                 {!hasBackUpCode && <div className="sub-heading">Enter the code generated by your authenticator app.</div>}
//                                 {hasBackUpCode && <div className="sub-heading">Enter one of your backup codes.</div>}
//                             </div>
//                             {!hasBackUpCode && (<div className="mb-2" >
//                                 <ReactCodeInput
//                                     type='text'
//                                     fields={6}
//                                     {...codeInputProps}
//                                 />
//
//                                 {/*<div className="mt-4">*/}
//                                 {/*    <span onClick={() => setHasBackUpCode(true)} className="brand-color cursor-pointer">*/}
//                                 {/*        Use a backup code instead.*/}
//                                 {/*    </span>*/}
//                                 {/*</div>*/}
//                             </div>
//                             )}
//                             {hasBackUpCode && (
//                                 <div className="p-3" >
//                                     <div className="form-outline mb-3">
//                                         <input
//                                             name="backupCode"
//                                             type="text"
//                                             autoComplete="off"
//                                             className={value && value.backupCode ? `form-control has-code` : `form-control seerbit-code`}
//                                             onChange={(e) => handleValue(e)}
//                                             value={value && value.backupCode}
//                                             required
//                                         />
//                                         <label className="form-label">Backup Code</label>
//                                     </div>
//
//                                     <div className="mt-4">
//                                         <span onClick={() => setHasBackUpCode(false)} className="brand-color cursor-pointer">
//                                             Use six digit auth code instead.
//                                         </span>
//                                     </div>
//                                 </div>
//                             )
//                             }
//                             <div className="my-5">
//                                 <Button
//                                     block
//                                     className="brand-btn h-50px"
//                                     type="submit"
//                                     disabled={inProcess}
//                                 >
//                                     {inProcess && (
//                                         <Spinner animation="border" variant="light" />
//                                     )}
//                                     {!inProcess && "Login"}
//                                 </Button>
//                             </div>
//                         </form>
//                     </div>
//                 </div>
//                 </div>
//                 <SeerBitAdverts/>
//             </div>
//         </div>
//     );
// }
//
// const mapStateToProps = (state) => ({
//     user_details: state.data.user_details,
//     error_details: state.data.error_details,
//     location: state.data.location,
//     white_label: state.data.white_label,
// });
//
// export default connect(mapStateToProps, { userLogin, setErrorLog })(PinCode);
